services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: job_globe
      POSTGRES_PASSWORD: job_globe
      POSTGRES_DB: job_globe
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
